INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('1', 'V41', 'Neural network model for biomass estimation', '2020-01-01');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('2', 'V56', 'Ensemble model for species identification', '2020-01-02');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('3', 'V19', 'Clustering model for forest density analysis', '2020-01-03');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('4', 'V96', 'Deep learning model for wood volume estimation', '2020-01-04');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('5', 'V25', 'Decision tree model for growth pattern prediction', '2020-01-05');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('6', 'V85', 'Linear regression model for tree height prediction', '2020-01-06');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('7', 'V63', 'Deep learning model for wood volume estimation', '2020-01-07');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('8', 'V24', 'Ensemble model for species identification', '2020-01-08');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('9', 'V36', 'Random forest model for species distribution', '2020-01-09');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('10', 'V18', 'Time series model for climate impact analysis', '2020-01-10');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('11', 'V67', 'Bayesian model for forest inventory prediction', '2020-01-11');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('12', 'V73', 'Deep learning model for wood volume estimation', '2020-01-12');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('13', 'V89', 'Neural network model for biomass estimation', '2020-01-13');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('14', 'V53', 'Random forest model for species distribution', '2020-01-14');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('15', 'V34', 'Time series model for climate impact analysis', '2020-01-15');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('16', 'V48', 'Clustering model for forest density analysis', '2020-01-16');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('17', 'V90', 'Deep learning model for wood volume estimation', '2020-01-17');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('18', 'V60', 'Ensemble model for species identification', '2020-01-18');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('19', 'V7', 'Neural network model for biomass estimation', '2020-01-19');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('20', 'V45', 'Random forest model for species distribution', '2020-01-20');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('21', 'V29', 'Decision tree model for growth pattern prediction', '2020-01-21');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('22', 'V83', 'Linear regression model for tree height prediction', '2020-01-22');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('23', 'V17', 'Clustering model for forest density analysis', '2020-01-23');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('24', 'V22', 'Deep learning model for wood volume estimation', '2020-01-24');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('25', 'V61', 'Ensemble model for species identification', '2020-01-25');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('26', 'V68', 'Time series model for climate impact analysis', '2020-01-26');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('27', 'V70', 'Bayesian model for forest inventory prediction', '2020-01-27');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('28', 'V30', 'Neural network model for biomass estimation', '2020-01-28');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('29', 'V79', 'Random forest model for species distribution', '2020-01-29');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('30', 'V100', 'Linear regression model for tree height prediction', '2020-01-30');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('31', 'V16', 'Decision tree model for growth pattern prediction', '2020-01-31');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('32', 'V43', 'Deep learning model for wood volume estimation', '2020-02-01');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('33', 'V13', 'Ensemble model for species identification', '2020-02-02');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('34', 'V91', 'Clustering model for forest density analysis', '2020-02-03');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('35', 'V26', 'Time series model for climate impact analysis', '2020-02-04');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('36', 'V1', 'Deep learning model for wood volume estimation', '2020-02-05');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('37', 'V38', 'Bayesian model for forest inventory prediction', '2020-02-06');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('38', 'V28', 'Random forest model for species distribution', '2020-02-07');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('39', 'V62', 'Neural network model for biomass estimation', '2020-02-08');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('40', 'V4', 'Linear regression model for tree height prediction', '2020-02-09');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('41', 'V92', 'Decision tree model for growth pattern prediction', '2020-02-10');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('42', 'V6', 'Clustering model for forest density analysis', '2020-02-11');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('43', 'V32', 'Deep learning model for wood volume estimation', '2020-02-12');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('44', 'V66', 'Time series model for climate impact analysis', '2020-02-13');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('45', 'V59', 'Ensemble model for species identification', '2020-02-14');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('46', 'V3', 'Random forest model for species distribution', '2020-02-15');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('47', 'V97', 'Neural network model for biomass estimation', '2020-02-16');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('48', 'V46', 'Linear regression model for tree height prediction', '2020-02-17');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('49', 'V78', 'Clustering model for forest density analysis', '2020-02-18');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('50', 'V39', 'Bayesian model for forest inventory prediction', '2020-02-19');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('51', 'V72', 'Deep learning model for wood volume estimation', '2020-02-20');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('52', 'V14', 'Time series model for climate impact analysis', '2020-02-21');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('53', 'V64', 'Decision tree model for growth pattern prediction', '2020-02-22');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('54', 'V88', 'Ensemble model for species identification', '2020-02-23');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('55', 'V50', 'Random forest model for species distribution', '2020-02-24');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('56', 'V93', 'Neural network model for biomass estimation', '2020-02-25');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('57', 'V86', 'Linear regression model for tree height prediction', '2020-02-26');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('58', 'V21', 'Clustering model for forest density analysis', '2020-02-27');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('59', 'V77', 'Deep learning model for wood volume estimation', '2020-02-28');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('60', 'V5', 'Time series model for climate impact analysis', '2020-02-29');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('61', 'V42', 'Ensemble model for species identification', '2020-03-01');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('62', 'V2', 'Bayesian model for forest inventory prediction', '2020-03-02');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('63', 'V55', 'Decision tree model for growth pattern prediction', '2020-03-03');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('64', 'V9', 'Neural network model for biomass estimation', '2020-03-04');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('65', 'V33', 'Random forest model for species distribution', '2020-03-05');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('66', 'V47', 'Clustering model for forest density analysis', '2020-03-06');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('67', 'V98', 'Deep learning model for wood volume estimation', '2020-03-07');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('68', 'V74', 'Ensemble model for species identification', '2020-03-08');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('69', 'V11', 'Linear regression model for tree height prediction', '2020-03-09');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('70', 'V23', 'Time series model for climate impact analysis', '2020-03-10');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('71', 'V52', 'Neural network model for biomass estimation', '2020-03-11');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('72', 'V35', 'Bayesian model for forest inventory prediction', '2020-03-12');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('73', 'V82', 'Decision tree model for growth pattern prediction', '2020-03-13');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('74', 'V54', 'Random forest model for species distribution', '2020-03-14');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('75', 'V31', 'Clustering model for forest density analysis', '2020-03-15');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('76', 'V58', 'Deep learning model for wood volume estimation', '2020-03-16');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('77', 'V20', 'Ensemble model for species identification', '2020-03-17');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('78', 'V44', 'Neural network model for biomass estimation', '2020-03-18');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('79', 'V12', 'Linear regression model for tree height prediction', '2020-03-19');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('80', 'V65', 'Time series model for climate impact analysis', '2020-03-20');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('81', 'V49', 'Random forest model for species distribution', '2020-03-21');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('82', 'V81', 'Decision tree model for growth pattern prediction', '2020-03-22');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('83', 'V75', 'Ensemble model for species identification', '2020-03-23');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('84', 'V15', 'Bayesian model for forest inventory prediction', '2020-03-24');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('85', 'V40', 'Clustering model for forest density analysis', '2020-03-25');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('86', 'V84', 'Deep learning model for wood volume estimation', '2020-03-26');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('87', 'V57', 'Neural network model for biomass estimation', '2020-03-27');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('88', 'V27', 'Time series model for climate impact analysis', '2020-03-28');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('89', 'V99', 'Linear regression model for tree height prediction', '2020-03-29');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('90', 'V69', 'Random forest model for species distribution', '2020-03-30');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('91', 'V10', 'Decision tree model for growth pattern prediction', '2020-03-31');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('92', 'V76', 'Clustering model for forest density analysis', '2020-04-01');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('93', 'V71', 'Ensemble model for species identification', '2020-04-02');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('94', 'V8', 'Neural network model for biomass estimation', '2020-04-03');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('95', 'V87', 'Deep learning model for wood volume estimation', '2020-04-04');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('96', 'V37', 'Time series model for climate impact analysis', '2020-04-05');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('97', 'V51', 'Linear regression model for tree height prediction', '2020-04-06');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('98', 'V95', 'Decision tree model for growth pattern prediction', '2020-04-07');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('99', 'V80', 'Random forest model for species distribution', '2020-04-08');
INSERT INTO DimModelVersion (ModelVersionKey, ModelVersion, ModelDescription, CreationDate) VALUES ('100', 'V66', 'Ensemble model for species identification', '2020-04-09');
