INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('1', 'Maple', 'Birch trees are known for their distinctive bark and are deciduous.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('2', 'Deciduous', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('3', 'Oak', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('4', 'Fir', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('5', 'Maple', 'Oak trees are large long-lived trees with strong wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('6', 'Ash', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('7', 'Spruce', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('8', 'Maple', 'Oak trees are large long-lived trees with strong wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('9', 'Oak', 'Cedar trees are large coniferous trees with durable wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('10', 'Fir', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('11', 'Deciduous', 'Pine trees are evergreen coniferous resinous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('12', 'Oak', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('13', 'Oak', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('14', 'Spruce', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('15', 'Cedar', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('16', 'Fir', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('17', 'Birch', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('18', 'Oak', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('19', 'Cedar', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('20', 'Birch', 'Willow trees are known for their slender flexible branches.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('21', 'Fir', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('22', 'Pine', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('23', 'Ash', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('24', 'Cedar', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('25', 'Willow', 'Pine trees are evergreen coniferous resinous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('26', 'Pine', 'Deciduous trees shed their leaves annually.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('27', 'Ash', 'Deciduous trees shed their leaves annually.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('28', 'Spruce', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('29', 'Maple', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('30', 'Deciduous', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('31', 'Willow', 'Deciduous trees shed their leaves annually.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('32', 'Spruce', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('33', 'Fir', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('34', 'Spruce', 'Cedar trees are large coniferous trees with durable wood.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('35', 'Maple', 'Birch trees are known for their distinctive bark and are deciduous.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('36', 'Fir', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('37', 'Willow', 'Willow trees are known for their slender flexible branches.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('38', 'Maple', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('39', 'Birch', 'Cedar trees are large coniferous trees with durable wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('40', 'Deciduous', 'Deciduous trees shed their leaves annually.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('41', 'Willow', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('42', 'Birch', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('43', 'Ash', 'Willow trees are known for their slender flexible branches.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('44', 'Willow', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('45', 'Ash', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('46', 'Fir', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('47', 'Birch', 'Willow trees are known for their slender flexible branches.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('48', 'Deciduous', 'Willow trees are known for their slender flexible branches.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('49', 'Maple', 'Deciduous trees shed their leaves annually.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('50', 'Oak', 'Willow trees are known for their slender flexible branches.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('51', 'Spruce', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('52', 'Pine', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('53', 'Deciduous', 'Cedar trees are large coniferous trees with durable wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('54', 'Birch', 'Oak trees are large long-lived trees with strong wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('55', 'Oak', 'Willow trees are known for their slender flexible branches.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('56', 'Deciduous', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('57', 'Birch', 'Pine trees are evergreen coniferous resinous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('58', 'Cedar', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('59', 'Cedar', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('60', 'Ash', 'Oak trees are large long-lived trees with strong wood.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('61', 'Deciduous', 'Cedar trees are large coniferous trees with durable wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('62', 'Cedar', 'Oak trees are large long-lived trees with strong wood.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('63', 'Birch', 'Willow trees are known for their slender flexible branches.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('64', 'Ash', 'Deciduous trees shed their leaves annually.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('65', 'Birch', 'Pine trees are evergreen coniferous resinous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('66', 'Ash', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('67', 'Deciduous', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('68', 'Oak', 'Deciduous trees shed their leaves annually.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('69', 'Maple', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('70', 'Willow', 'Birch trees are known for their distinctive bark and are deciduous.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('71', 'Oak', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('72', 'Fir', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('73', 'Birch', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('74', 'Fir', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('75', 'Oak', 'Oak trees are large long-lived trees with strong wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('76', 'Ash', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('77', 'Willow', 'Pine trees are evergreen coniferous resinous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('78', 'Willow', 'Birch trees are known for their distinctive bark and are deciduous.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('79', 'Pine', 'Birch trees are known for their distinctive bark and are deciduous.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('80', 'Willow', 'Cedar trees are large coniferous trees with durable wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('81', 'Maple', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('82', 'Willow', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('83', 'Oak', 'Pine trees are evergreen coniferous resinous trees.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('84', 'Pine', 'Pine trees are evergreen coniferous resinous trees.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('85', 'Oak', 'Spruce trees are coniferous and typically found in northern temperate and boreal regions.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('86', 'Oak', 'Birch trees are known for their distinctive bark and are deciduous.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('87', 'Spruce', 'Fir trees are a genus of 48–55 species of evergreen coniferous trees.', 'Coniferous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('88', 'Pine', 'Ash trees are tall trees with compound leaves and a straight trunk.', 'Evergreen');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('89', 'Oak', 'Cedar trees are large coniferous trees with durable wood.', 'Deciduous');
INSERT INTO DimSpecies (SpeciesKey, SpeciesName, SpeciesDescription, SpeciesType) VALUES ('90', 'Spruce', 'Maple trees are known for their vibrant fall colors and sap used for syrup.', 'Coniferous');
